# FreeCodeCamp
## Deep Learning for Computer Vision with Python and TensorFlow – Complete Course

<iframe width="560" height="315" src="https://www.youtube.com/embed/IA3WxTTPXqQ?si=L6oOsfpXhVXGqmxt" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

(37:00/1:13:16:40)

## Advanced Computer Vision with Python - Full Course

<iframe width="560" height="315" src="https://www.youtube.com/embed/01sAkU_NvOY?si=A-0qwbZsVbRSCDFA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

(3:30/6:40:40)

## OpenCV Course - Full Tutorial with Python

<iframe width="560" height="315" src="https://www.youtube.com/embed/oXlwWbU8l2o?si=2dvvGAxeLdYbqF0Y" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

# Michigan Online
## Deep Learning for Computer Vision
### Lecture 1: Introduction to Deep Learning for Computer Vision

# Crash Course
## Computer Vision: Crash Course Computer Science #35
<iframe width="560" height="315" src="https://www.youtube.com/embed/-4E2-0sxVUM?si=F1IZseXiGP3uMUHm" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

# Computer vision engineer

## OpenCV tutorial for beginners | FULL COURSE in 3 hours with Python

<iframe width="560" height="315" src="https://www.youtube.com/embed/eDIj5LuIL4A?si=7tNlSrFj77cMC9C1" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Computer Vision Roadmap [UPDATED 2023] | How to become a computer vision engineer (Watched)

<iframe width="560" height="315" src="https://www.youtube.com/embed/DalV5No4c_0?si=bVHxKtRqxRdXqiL_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Computer vision roadmap | How to become a computer vision engineer (Watched)

<iframe width="560" height="315" src="https://www.youtube.com/embed/DfPAvepK5Ws?si=VoAin29r0qnKi9Jo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Object detection with Python FULL COURSE | Computer vision

<iframe width="560" height="315" src="https://www.youtube.com/embed/UL2cfTTqdNo?si=3YozEFmYlgvWyN8M" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

# Nicholas Renotte
## Tensorflow Object Detection in 5 Hours with Python | Full Course with 3 Projects

<iframe width="560" height="315" src="https://www.youtube.com/embed/yqkISICHH-U?si=vd8DGnn97fmfm-Rn" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

- https://github.com/nicknochnack/TFODCourse
- https://github.com/nicknochnack/TFODApp

# Murtaza's Workshop - Robotics and AI

## Top 25 Computer Vision Projects 2021

<iframe width="560" height="315" src="https://www.youtube.com/embed/BFlRmIvqwSA?si=WHdg-cLbZeQxJIwf" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## 100 Computer Vision Projects for 2023

<iframe width="560" height="315" src="https://www.youtube.com/embed/Q16PMyIIE3Y?si=qkQHvyVjJGN9fAf-" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> 

1. Background Removal
2. Distance Measurement
3. Traffic Sign Classification
4. Multiple Hand Gesture Control
5. Virtual Zoom Gesture
6. Hand Pose Detection
7. Virtual Quiz Game
8. AR Projects with Computer Vision
9. Finger Counting
10. Hand Gesture Drone
11. Document Scanner
12. QR/Bar Code Detection
13. Face Door Lock
14. Face Filter
15. Self Driving Simulation
16. Feature Detection 
17. Angle Finder
18. Panaroma Stretching
19. OCR using Computer Vision
20. Sudoku Solver
21. Drone Path Visualiser
22. Lane Following Drone
23. Text Detection
24. Custom Object Detection
25. Face Detection
26. Object Tracking
27. Optical Mark Recognition
28. Obstacle Avoiding Robot
29. Lamp Gesture Control
30. Face Emotion Detector
31. Shape Detection
32. Object Size Measurement
33. Virtual Calculator
34. Velcro Dart Game
35. Red Light Green Light
36. Cookie Cutter
37. Personal AI Trainer
38. Track and Shoot
39. Elbow Pose Detector
40. AI Mouse Control
41. Custom Object Counter
42. Robot Hand Gesture Control
43. Virtual Keyboard
44. Self Driving
45. AI Virtual Painter
46. Balloon Pop Pygame
47. Object Detection Mobile App
48. Face Tracking
49. Eye Tracking
50. Deep Fake
51. Balloon Pop Game
52. Basketball Shot Predictor
53. Hand Distance Measurement
54. Parking Space Counter
55. Volume Gesture Control
56. Drone Body Following
57. Fruit Classifier
58. Color Detection
59. Face Mesh
60. Body Pose Detection
61. Drowsiness Detection

## Hand Tracking 30 FPS using CPU | OpenCV Python (2021) | Computer Vision

<iframe width="560" height="315" src="https://www.youtube.com/embed/NZde8Xt78Iw?si=rCH34PhqJF0M4PIl" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

(7:00/48:59)

`The code is not running`


In [2]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [1]:
!pip install -q mediapipe

zsh:1: command not found: wget


In [4]:
# Use of MediaPipe for Hand Tracking using CPU
# installed opencv-python, mediapipe
import cv2
import time
import mediapipe as mp

cap = cv2.VideoCapture(0)
mpHands = mp.solutions.hands 
hands = mpHands.Hands(False)
mpDraw = mp.solutions.drawing_utils
pTimer = 0
cTimer = 0

while True:
    success, img = cap.read()
    imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    results = hands.process(imgRGB)

    #print(results.multi_hand_landmark)
    if results.multi_hand_landmarks:
        for handLms in results.multi_hand_landmarks:
            for id, lm in enumerate(handLms.landmark):
                h,w,c = img.shape
                cx, cy = int(lm.x*w), int(lm.y*h)
                print(id, cx, cy)
                if id == 0:
                    cv2.circle(img, (cx,cy), 15, (255,0,255), cv2.FILLED)
            mpDraw.draw_landmarks(img, handLms, mpHands.HAND_CONNECTIONS)

    cTimer = time.time()
    fps = 1/(cTimer-pTimer)
    pTimer = cTimer

    cv2.putText(img, str(int(fps)), (10,70), cv2.FONT_HERSHEY_PLAIN, 3, (255,0,255), 3)

    cv2.imshow("Image",img)
    cv2.waitKey(1)


I0000 00:00:1723275600.589377  425162 gl_context.cc:357] GL version: 2.1 (2.1 Metal - 88.1), renderer: Apple M2
W0000 00:00:1723275600.609952  436371 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1723275600.621250  436371 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
/Users/shashankashekharsharma/anaconda3/lib/python3.11/site-packages/google/protobuf/symbol_database.py:55: UserWarning: SymbolDatabase.GetPrototype() is deprecated. Please use message_factory.GetMessageClass() instead. SymbolDatabase.GetPrototype() will be removed soon.
  warnings.warn('SymbolDatabase.GetPrototype() is deprecated. Please '


0 509 1147
1 690 1144
2 864 1077
3 1026 1026
4 1176 1017
5 858 823
6 1028 678
7 1141 589
8 1234 513
9 744 745
10 874 546
11 973 416
12 1054 298
13 608 723
14 655 489
15 689 334
16 722 207
17 467 753
18 439 554
19 414 430
20 402 313
0 617 883
1 798 903
2 985 836
3 1149 770
4 1302 744
5 1001 554
6 1166 426
7 1279 340
8 1372 256
9 893 461
10 1022 276
11 1112 156
12 1181 50
13 762 430
14 821 230
15 867 95
16 906 -18
17 615 453
18 607 269
19 603 145
20 607 29
0 535 962
1 769 929
2 982 840
3 1151 767
4 1315 736
5 983 570
6 1135 445
7 1243 361
8 1338 283
9 877 489
10 981 323
11 1061 212
12 1134 115
13 751 451
14 806 277
15 852 131
16 907 0
17 602 465
18 598 291
19 597 168
20 607 47
0 626 776
1 861 741
2 1076 663
3 1246 591
4 1392 548
5 1093 383
6 1265 263
7 1375 174
8 1467 96
9 993 297
10 1118 127
11 1202 14
12 1278 -80
13 874 257
14 943 84
15 993 -52
16 1046 -168
17 729 262
18 740 104
19 753 -11
20 779 -119
0 739 617
1 951 596
2 1150 533
3 1319 465
4 1467 429
5 1183 256
6 1354 143
7 1467 53


KeyboardInterrupt: 

# Krish Naik
## Complete RoadMap To Learn Computer Vision (Watched)

<iframe width="560" height="315" src="https://www.youtube.com/embed/jLcuVu5xdDo?si=TWAaZfgkGxQg5SSM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

# Computer Vision — Andreas Geiger

[Computer Vision - Lecture 1.1 (Introduction: Organization)](https://www.youtube.com/watch?v=YW1cIaOBkI8&list=PL05umP7R6ij35L2MHGzis8AEHz7mg381_)

<iframe width="560" height="315" src="https://www.youtube.com/embed/YW1cIaOBkI8?si=bhsynuTTvXYnNaGR" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

[Computer Vision - Lecture 1.2 (Introduction: Introduction)](https://www.youtube.com/watch?v=mQgjfvjjW3Q&list=PL05umP7R6ij35L2MHGzis8AEHz7mg381_&index=2)


<iframe width="560" height="315" src="https://www.youtube.com/embed/mQgjfvjjW3Q?si=Ln0CU1iZxvo9Zpue" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

[Computer Vision - Lecture 1.3 (Introduction: History of Computer Vision)](https://www.youtube.com/watch?v=hCewSTTOt_4&list=PL05umP7R6ij35L2MHGzis8AEHz7mg381_&index=3)

<iframe width="560" height="315" src="https://www.youtube.com/embed/hCewSTTOt_4?si=BourHUijDxA6Rris" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Resources 
[Lecture Resources](https://uni-tuebingen.de/fakultaeten/mathematisch-naturwissenschaftliche-fakultaet/fachbereiche/informatik/lehrstuehle/autonomous-vision/lectures/computer-vision/)

# Topics to Learn
1. Statistics
2. SDG
3. Adagrad
4. RMSProp
5. Adam
6. Introduction to Neural Network
7. Loss Function
8. Optimizers
9. Gradient Descent
10. Convolutional Neural Network
11. Image Processing
12. Transfer Learning
    1.  Alexnet
    2.  VGG16
    3.  VGG19
    4.  RESNET
13. Object Detection
    1.  RCNN
    2.  SSD
    3.  YOLO
14. Important Libraries
    1.  OpenCV
    2.  TensorFlow
    3.  PyTorch
15. Software Skills
    1.  Docker
    2.  Cloud

# Resources
[Computer Vision Resources](https://coggle.it/diagram/ZO5EUOut86Irr5hc/t/computer-vision-roadmap/760d909a1f28af1782645ff9b5af1dfd4481ce08bf258b4b54f868d7f3a1b8d5)

# Project Ideas
1. Color Detection
2. QR Reader
3. Random Flag Generator
4. Lane Crossing Detection
5. Object Detection
6. Image Classification
7. Face Attendance System
8. Generative Adversarial Network
9. Implement State of the art paper on Computer Vision

In [2]:
pip install tensorflow

  Using cached termcolor-2.4.0-py3-none-any.whl.metadata (6.1 kB)
  Using cached numpy-1.26.4-cp312-cp312-macosx_11_0_arm64.whl.metadata (61 kB)
  Using cached rich-13.7.1-py3-none-any.whl.metadata (18 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.8/47.8 kB 4.9 MB/s eta 0:00:00
  Using cached tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
  Using cached MarkupSafe-2.1.5-cp312-cp312-macosx_10_9_universal2.whl.metadata (3.0 kB)
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 236.3/236.3 MB 633.3 kB/s eta 0:00:0000:0100:10
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.7/133.7 kB 300.8 kB/s eta 0:00:0000:0100:01
Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 788.5 kB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━

In [3]:
import tensorflow as tf

In [5]:
zero_d = tf.constant(5)
print(zero_d)

tf.Tensor(5, shape=(), dtype=int32)


In [7]:
one_d = tf.constant([1, 2, 3])
print(one_d)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [9]:
two_d = tf.constant([[1, 2, 3], [4, 5, 6]])
print(two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [10]:
three_d = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(three_d)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [11]:
four_d = tf.constant([[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], [[[13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24]]]])
print(four_d)

tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]], shape=(2, 2, 2, 3), dtype=int32)


In [13]:
casted_four_d = tf.cast(four_d, tf.float32)
print(casted_four_d)

tf.Tensor(
[[[[ 1.  2.  3.]
   [ 4.  5.  6.]]

  [[ 7.  8.  9.]
   [10. 11. 12.]]]


 [[[13. 14. 15.]
   [16. 17. 18.]]

  [[19. 20. 21.]
   [22. 23. 24.]]]], shape=(2, 2, 2, 3), dtype=float32)


In [14]:
import numpy as np

In [15]:
arr1 = np.array([1,2,3,4,5])
print(arr1)


[1 2 3 4 5]


In [17]:
converted_arr1 = tf.convert_to_tensor(arr1)
print(converted_arr1)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int64)


To access all the important libraries of OpenCV

In [2]:
pip install opencv-contrib-python

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.7/63.7 MB 157.3 kB/s eta 0:00:0000:0100:05
Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install opencv-python

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.8/54.8 MB 2.2 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


In [1]:
import cv2
image = cv2.imread('athar-khan-Y9D4hZWB4kI-unsplash.jpg')
print(type(image))

<class 'numpy.ndarray'>


OpenCV considers an image as an numpy array

In [2]:
print(image.shape)

(3456, 5184, 3)


`image.shape` gives three paramers which are height, width and number of channels

Images are made of pixels. Most of the images have pixel range of 0 to 255. In binary images the pixel value is in [0,1]\(or[0,255]\).

In 16 bit images, pixel value range from 0 to 65525

# Two main matrix of evaluation in Object Detection
1. **Intersection Over Union**: How good is the predictied bounding box compared to the ground truth. The value is always between 0 and 1 wherin 1 means perfect overlap and no overlap means 0

$$
\text{IoU} = \frac{\text{Area of Intersection between the bounding boxes}}{\text{Area of Union between the bounding boxes}}
$$


## Average Precision

**Confusion Matrix**
The confusion matrix is a tool used to understand the performance of a classification model, which is a type of machine learning model that predicts which category or class an item belongs to

Imagine you're a doctor diagnosing patients as either having a disease (Positive) or not having it (Negative) based on some medical test.

When the test results come in, there are four possible outcomes for each patient:

- True Positive (TP): The test correctly predicts that the patient has the disease.
- True Negative (TN): The test correctly predicts that the patient does not have the disease.
- False Positive (FP): The test incorrectly predicts that the patient has the disease (also known as a "false alarm").
- False Negative (FN): The test incorrectly predicts that the patient does not have the disease (missed diagnosis).

The confusion matrix for a binary classifier can be visualized as:

$$
\begin{array}{c|c|c}
\text{} & \text{Predicted Positive} & \text{Predicted Negative} \\
\hline
\text{Actual Positive} & \text{True Positive (TP)} & \text{False Negative (FN)} \\
\hline
\text{Actual Negative} & \text{False Positive (FP)} & \text{True Negative (TN)} \\
\end{array}
$$

Using the confusion matrix, you can calculate various performance metrics:

- **Accuracy**: This measures how often the model is correct.
  $$
  \text{Accuracy} = \frac{TP + TN}{TP + TN + FP + FN}
  $$

- **Precision**: This tells us how many of the predicted positive cases were actually positive.
  $$
  \text{Precision} = \frac{TP}{TP + FP}
  $$

- **Recall (Sensitivity)**: This tells us how many of the actual positive cases were correctly predicted.
  $$
  \text{Recall} = \frac{TP}{TP + FN}
  $$

- **F1 Score**: This is the harmonic mean of Precision and Recall, providing a single metric that balances both.
  $$
  \text{F1 Score} = 2 \times \frac{\text{Precision} \times \text{Recall}}{\text{Precision} + \text{Recall}}
  $$




2. **Mean Average Precision (mAP)**

Mean Average Precision (mAP) is a metric used to evaluate the performance of object detection models, which are a type of machine learning model designed to locate and classify objects within images. It combines precision and recall across different thresholds and classes, providing a comprehensive measure of a model's accuracy.

To understand mAP, we need to break it down into its core components:

1. **Precision**: Precision is the ratio of correctly predicted positive observations to the total predicted positives. It answers the question, "Of all the objects detected, how many were correct?"

   $$
   \text{Precision} = \frac{\text{True Positives (TP)}}{\text{True Positives (TP)} + \text{False Positives (FP)}}
   $$

2. **Recall**: Recall is the ratio of correctly predicted positive observations to all observations in the actual class. It answers the question, "Of all the actual objects, how many were detected correctly?"

   $$
   \text{Recall} = \frac{\text{True Positives (TP)}}{\text{True Positives (TP)} + \text{False Negatives (FN)}}
   $$

### Precision-Recall Curve

The performance of an object detection model can be visualized using a precision-recall curve, which plots precision against recall at various threshold settings. A high area under the curve represents both high recall and high precision, indicating good performance.

### Average Precision (AP)

Average Precision (AP) summarizes the precision-recall curve into a single value, taking the average precision over all recall values from 0 to 1. This involves calculating the precision at different recall levels and then averaging them. The AP is typically computed for each class in a multi-class problem.

$$
\text{AP} = \int_0^1 \text{Precision}(\text{Recall}) \, d\text{Recall}
$$

### Mean Average Precision (mAP)

Mean Average Precision (mAP) is the average of the APs over all classes. If we have \(N\) classes, the mAP is calculated as follows:

$$
\text{mAP} = \frac{1}{N} \sum_{i=1}^{N} \text{AP}_i
$$

Where \(\text{AP}_i\) is the average precision for class \(i\).

### Steps to Calculate mAP

1. **Compute Precision and Recall**: For each detected object, compare it with the ground truth to determine if it is a true positive or false positive. Calculate precision and recall for various threshold levels.

2. **Plot Precision-Recall Curve**: For each class, plot the precision-recall curve.

3. **Calculate Average Precision (AP)**: Integrate the area under the precision-recall curve to get the AP for each class.

4. **Compute Mean Average Precision (mAP)**: Average the APs across all classes to get the mAP.

### Why mAP is Important

mAP is a comprehensive metric for evaluating object detection models because it considers both the precision and recall across different thresholds and for multiple classes. It provides a balanced measure of a model's ability to accurately detect objects (precision) and to detect as many objects as possible (recall).

By optimizing for mAP, we ensure that the model performs well across various scenarios and object classes, making it a reliable metric for real-world applications of object detection.


![img](IMG_5769FBABE05B-1.jpeg)

# Object Detection
Object Detection is a computer vision technique to identify and locate objects within images and videos

## Technologies to perform object detection
- Mediapipe
- OpenCV
- Yolov8
- Detectron2
- AWS Rekognition

# Projects to Work on

### 1. **Face Recognition System**
   - **Description:** Build a face recognition system that can identify individuals in real-time using a webcam or from a pre-recorded video.
   - **Key Concepts:** Face detection (using Haar Cascades or deep learning models), face recognition (using LBPH, Eigenfaces, or deep learning techniques like FaceNet), and real-time video processing.

### 2. **Object Detection and Tracking**
   - **Description:** Develop a system that can detect and track multiple objects in a video stream. You can use pre-trained models like YOLO, SSD, or use OpenCV's built-in methods for object tracking.
   - **Key Concepts:** Object detection, tracking algorithms (e.g., KCF, CSRT), and motion analysis.

### 3. **Virtual Paint Application**
   - **Description:** Create an application where users can draw on the screen using gestures detected by a webcam. The system should recognize hand movements and translate them into drawing actions.
   - **Key Concepts:** Hand gesture recognition, color detection, and image processing.

### 4. **License Plate Recognition**
   - **Description:** Develop a system to automatically recognize vehicle license plates from images or videos. This can be applied to parking systems or traffic monitoring.
   - **Key Concepts:** Character recognition (using OCR), image segmentation, and morphological operations.

### 5. **Augmented Reality with OpenCV**
   - **Description:** Create an AR application where virtual objects (e.g., 3D models) are superimposed on real-world video streams. For example, placing virtual furniture in a room.
   - **Key Concepts:** Feature detection and matching (using ORB, SIFT), homography, and camera calibration.

### 6. **Document Scanner and OCR**
   - **Description:** Build a document scanning application that can detect the edges of a document, apply perspective transformation, and extract text using Optical Character Recognition (OCR).
   - **Key Concepts:** Edge detection, perspective transformation, and OCR (using Tesseract).

### 7. **Real-Time Drowsiness Detection**
   - **Description:** Implement a system that monitors a driver’s face and eyes to detect signs of drowsiness in real-time, alerting them when necessary.
   - **Key Concepts:** Eye detection, facial landmarks, and blinking rate analysis.

### 8. **Gesture-Controlled Robot**
   - **Description:** Use hand gestures to control a robot or a virtual character. The gestures can be detected via a webcam and translated into commands for the robot.
   - **Key Concepts:** Gesture recognition, motion detection, and control systems.

### 9. **Automatic Image Enhancement**
   - **Description:** Create an application that automatically enhances the quality of images by adjusting brightness, contrast, sharpness, and removing noise.
   - **Key Concepts:** Histogram equalization, image filtering, and noise reduction techniques.

### 10. **Barcode and QR Code Scanner**
   - **Description:** Develop a scanner that can detect and decode barcodes and QR codes from images or real-time video feeds.
   - **Key Concepts:** Image thresholding, contour detection, and decoding algorithms.


In [4]:
pip install opencv-python pyzbar

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install --upgrade pip

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 997.4 kB/s eta 0:00:000:00:010m
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Uninstalling pip-24.1.2:
      Successfully uninstalled pip-24.1.2
Note: you may need to restart the kernel to use updated packages.


# The basic steps involved in digital image processing are:
- _Image acquisition_: This involves capturing an image using a digital camera or scanner, or importing an existing image into a computer.
- _Image enhancement_: This involves improving the visual quality of an image, such as increasing contrast, reducing noise, and removing artifacts.
- _Image restoration_: This involves removing degradation from an image, such as blurring, noise, and distortion.
- _Image segmentation_: This involves dividing an image into regions or segments, each of which corresponds to a specific object or feature in the image.
- _Image representation and description_: This involves representing an image in a way that can be analyzed and manipulated by a computer, and describing the features of an image in a compact and meaningful way.
- _Image analysis_: This involves using algorithms and mathematical models to extract information from an image, such as recognizing objects, detecting patterns, and quantifying features.
- _Image synthesis and compression_: This involves generating new images or compressing existing images to reduce storage and transmission requirements.
Digital image processing is widely used in a variety of applications, including medical imaging, remote sensing, computer vision, and multimedia.

In [2]:
pip install mediapipe

  Using cached protobuf-4.25.4-cp37-abi3-macosx_10_9_universal2.whl.metadata (541 bytes)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 MB 18.4 MB/s eta 0:00:0000:0100:01
Using cached protobuf-4.25.4-cp37-abi3-macosx_10_9_universal2.whl (394 kB)
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.3
    Uninstalling protobuf-3.20.3:
      Successfully uninstalled protobuf-3.20.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.22.0 requires protobuf<4,>=3.12, but you have protobuf 4.25.4 which is incompatible.
Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install opencv-python


  Using cached opencv_python-4.10.0.84-cp37-abi3-macosx_11_0_arm64.whl.metadata (20 kB)
Using cached opencv_python-4.10.0.84-cp37-abi3-macosx_11_0_arm64.whl (54.8 MB)
Note: you may need to restart the kernel to use updated packages.
